name: Deploy on PR Merge

on:
  pull_request:
    branches:
      - dev
      - main
    types:
      - closed
  push:
    branches:
      - dev

env:
  PROJECT_ID: avinashvidyarthi
  REGION: us-central1
  REPO_NAME: hello-world-cicd-demo
  DEV_SERVICE: hello-world-dev
  PROD_SERVICE: hello-world-prod

jobs:
  deploy:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Set deployment vars
        id: deploy_vars
        run: |
          if [[ "${{ github.base_ref }}" == "dev" ]]; then
            echo "SERVICE=$DEV_SERVICE" >> $GITHUB_ENV
            echo "IMAGE_NAME=gcr.io/$PROJECT_ID/$REPO_NAME/hello-world-dev" >> $GITHUB_ENV
          elif [[ "${{ github.base_ref }}" == "prod" ]]; then
            echo "SERVICE=$PROD_SERVICE" >> $GITHUB_ENV
            echo "IMAGE_NAME=gcr.io/$PROJECT_ID/$REPO_NAME/hello-world-prod" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "SERVICE=$DEV_SERVICE" >> $GITHUB_ENV
            echo "IMAGE_NAME=gcr.io/$PROJECT_ID/$REPO_NAME/hello-world-dev" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build . \
            --tag ${IMAGE_NAME}:latest \
            --tag ${IMAGE_NAME}:${{ github.sha }}

      - name: Push Docker image to Artifact Registry
        run: docker push ${IMAGE_NAME} --all-tags

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE } \
            --image ${IMAGE_NAME}:${{ github.sha }} \
            --region ${REGION} \
            --allow-unauthenticated
