name: Deploy on PR Merge

on:
  pull_request:
    branches:
      - dev
      - prod
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: portfolio
      REGION: us-central1
      REPO_NAME: hello-world-cicd-demo
      DEV_SERVICE: dev-service
      PROD_SERVICE: dev-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Set deployment vars
        id: deploy_vars
        run: |
          if [[ "${{ github.base_ref }}" == "dev" ]]; then
            echo "SERVICE=$DEV_SERVICE" >> $GITHUB_ENV
            echo "DEV_IMAGE_NAME=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/hello-world-dev" >> $GITHUB_ENV
            echo "IMAGE_NAME=$DEV_IMAGE_NAME" >> $GITHUB_ENV
          elif [[ "${{ github.base_ref }}" == "prod" ]]; then
            echo "SERVICE=$PROD_SERVICE" >> $GITHUB_ENV
            echo "PROD_IMAGE_NAME=gcr.io/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/hello-world-prod" >> $GITHUB_ENV
            echo "IMAGE_NAME=$PROD_IMAGE_NAME" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build . \
            --tag ${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Push Docker image to Artifact Registry
        run: docker push ${{ env.IMAGE_NAME }} --all-tags

      # - name: Deploy to Cloud Run
      #   run: |
      #     gcloud run deploy ${{ env.SERVICE }} \
      #       --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
      #       --region ${{ env.REGION }} \
      #       --platform managed \
      #       --allow-unauthenticated
